# Generated by Django 3.2 on 2021-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='responseMsg',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='sendMsg',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
