# Generated by Django 3.2 on 2021-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='size',
            field=models.IntegerField(default=None),
        ),
    ]
