# Generated by Django 3.2 on 2021-05-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0003_reservation_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
