# Generated by Django 3.2 on 2021-05-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('Table', '0006_alter_restaurant_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.accounttype'),
        ),
    ]
