# Generated by Django 3.2 on 2021-05-31 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0014_alter_reservation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/preview'),
        ),
        migrations.CreateModel(
            name='RestaurantPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/restaurant/<django.db.models.fields.related.ForeignKey>/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Table.restaurant')),
            ],
        ),
    ]
