# Generated by Django 3.2 on 2021-05-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0015_auto_20210531_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cousine',
            new_name='cuisines',
        ),
    ]
